### ISSUE TITLE
Any solution that can solve the problem?

### ISSUE THREAD

**Issue by Congrool** [MaciejPolanski/v_mremap#1]
Hi, I am encountered the similar problem when using mremap. I found the repo through the issue on [stackoverflow](https://stackoverflow.com/questions/72880778/syscall-mremap-does-not-work-as-i-expected-is-it-bugged-is-there-any-other-w).

I saw that there's mremap_around.c in this repo. I've tried it but still got error `Bad Address`. I am curious about that did you find the solution to solve it?

**Comment by MaciejPolanski** [comment]
Unfortunately, I haven't found a solution.

I asked my question after looking answers over the internet and my conclusion is that people developing Kernel do not consider this an error. Coalescing memory areas is not planed or desired.

So I just give up on this approach.

**Comment by Congrool** [comment]
I also get the same conclusion, anyway, thanks for your reply to the question a year ago. 
I can share my findings if you have interest 😄 :

I found a internal kernel function that may do the contiguous vmas merge, called [`vma_merge`](https://rus-linux.net/MyLDP/BOOKS/VirtMem/node33.html#5.4.6%20Merging%20contiguous%20regions:~:text=and%20vm_next_share()%20fields.-,5.4.6%20Merging%20contiguous%20regions,-Linux%20used%20to), which is only used inside the kernel and not exposed for user program. Thus, there's no way to call it without any kernel hack. 
Some syscall invokes it to merge memory, including `brk`, `mmap` and `mremap`. It is easy to demonstrate it for `mmap` with the following code:
```c
addr1 = mmap(NULL, SIZE1, PROT_WRITE | PROT_READ, MAP_ANONYMOUS | MAP_PRIVATE | MAP_POPULATE, -1, 0);
addr2 = mmap(addr1 + SIZE1, SIZE2, PROT_WRITE | PROT_READ,
		   MAP_ANONYMOUS | MAP_PRIVATE | MAP_FIXED | MAP_POPULATE, -1, 0);
```

Though it allocates two mappings, the final mapping you will find is only `[addr1, addr1 + SIZE1 + SIZE2)`, which is automatically merged during syscall.

However, it's not all of the case for [mremap](https://github.com/torvalds/linux/blob/f0b0d403eabbe135d8dbb40ad5e41018947d336c/mm/mremap.c#L1049-L1054).  Only in some case, it could do the automatic vma merge.


So, I have to give up the approach as you did😢 .

**Comment by Congrool** [comment]
Good luck, and I have to start my work from scratch.
